export const PLANS = [
  {
    name: 'Starter' as const,
    price: 4.99,
    storageLimit: 5,
    cpuCores: 1,
    ram: 1,
    features: [
      '5 GB SSD Storage',
      'Gestion 1 site web',
      'Déploiement automatique',
      'Support email',
      '30 jours essai gratuit',
    ],
    hasToolAccess: false,
  },
  {
    name: 'Professional' as const,
    price: 9.99,
    storageLimit: 15,
    cpuCores: 2,
    ram: 4,
    features: [
      '15 GB SSD Storage',
      'Sites illimités',
      'Déploiement automatique',
      'Intégration AdSense',
      'Support prioritaire 24/7',
      '30 jours essai gratuit',
    ],
    hasToolAccess: true,
  },
  {
    name: 'Enterprise' as const,
    price: 16.99,
    storageLimit: 100,
    cpuCores: 4,
    ram: 16,
    features: [
      '100 GB SSD Storage',
      'Sites illimités',
      'Déploiement automatique',
      'Intégration AdSense',
      'Provisioning avancé',
      'Support prioritaire 24/7',
      'API d\'accès complet',
      '30 jours essai gratuit',
    ],
    hasToolAccess: true,
  },
];
